name: 04- Using Actions

on: 
  workflow_dispatch:
#on: push


jobs:
    build:
        runs-on: ubuntu-latest
        # step is for all jobs
        defaults:
            run:
                working-directory: 04-using-action/react-app
        steps:
        # 0. Checkout the code from the repository
            - name: Checkout Code
              uses: actions/checkout@v4
        # 1. Install deps of our react applicaction
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
             
        # 2. Execute automated tests
            - name: Run Unit Tests
              run: npm run test
