name: 09 - Using Functions
on: 
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Prin PR title
              run: echo "${{github.event.pull_request}}"
            - name: Print PR Labels
              run: |
                cat << EOF
                ${{toJson(github.event.pull_request)}}
                EOF
            - name: Bug step
              if: ${{!cancelled() && contains(github.event.pull_request,'fix')}}
              run:  echo " I am a bug Fix"
            - name: Failing step
              run: exit 1
            - name: I will be skipped
              if: ${{success()}}
              run: echo "I will print if previous steps succeed"
            - name: I will execute
              if: ${{failure()}}
              run: echo "I will print if previous steps fails"
            - name: I will execute
              if: ${{!cancelled()}}  
              run: echo "I will print, except when the workflow is cancelled"
            - name: I will execute when cancelled
              if: ${{cancelled()}}
              run: echo "I will print if the workflow has been cancelled"